{
 "title": "RustamPW",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le,container,method,uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 99%",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,method,uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 95%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,method,uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 50%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,method,uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (container,method,uri) (rate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (method,uri) (rate(http_server_requests_seconds_count{uri!~\"/actuator.*\",status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{pod=~'otuspw-.*'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod) (container_memory_working_set_bytes{pod=~'otuspw-.*'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_database_size_bytes{datname='dz8_base'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_inserted{datname='dz8_base'}[1m])",
     "legendFormat": "Inserted"
    },
    {
     "expr": "increase(pg_stat_database_tup_deleted{datname='dz8_base'}[1m])",
     "legendFormat": "Deleted"
    },
    {
     "expr": "increase(pg_stat_database_tup_updated{datname='dz8_base'}[1m])",
     "legendFormat": "Updated"
    }
   ]
  }
 ]
}