postgresql:
  global:
    postgresql:
      auth:
        existingSecret: "{{ .Release.Name }}-pgsecret"
        username: rustam
        database: dz8_base
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/bitnami-shell

redis:
  image:
    name: redis:8.2.3

metrics:
  serviceMonitor:
    enabled: true

replicaCount: 1

image:
  orderServiceImage: rustamalimuradov/order-service:v30
  storageServiceImage: rustamalimuradov/storage-service:v17
  billingServiceImage: rustamalimuradov/billing-service:v18
  deliveryServiceImage: rustamalimuradov/delivery-service:v23
  fbeServiceImage: rustamalimuradov/fbe-service:v29
  clientMessagingServiceImage: rustamalimuradov/client-messaging-service:v8

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true