postgresql:
  global:
    postgresql:
      auth:
        existingSecret: "{{ .Release.Name }}-pgsecret"
        username: rustam
        database: dz8_base
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/bitnami-shell

metrics:
  serviceMonitor:
    enabled: true

replicaCount: 1

image:
  orderServiceImage: rustamalimuradov/order-service:v24
  storageServiceImage: rustamalimuradov/storage-service:v16
  billingServiceImage: rustamalimuradov/billing-service:v17
  deliveryServiceImage: rustamalimuradov/delivery-service:v20
  fbeServiceImage: rustamalimuradov/fbe-service:v27
  clientMessagingServiceImage: rustamalimuradov/client-messaging-service:v7

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true