appCfgPath: ${APP_CONFIG_PATH:/config}

spring:
  application:
    name: order-service
  config:
    import:
      - file:${appCfgPath}/db.yaml
  rabbitmq:
    connection-timeout: 10000
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      database: 0
      port: 6379
      host: ${RELEASE_NAME:otuspw}-redis-service
      timeout: 10000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
    export:
      prometheus:
        enabled: true

server:
  port: ${APP_HTTP_PORT:8000}

logging:
  level:
    root: "info"
    ru.rustam: "debug"